CC=gcc
CFLAGS=-O2 
LINK=-O2 -lncurses
SRC=game.c ncurses_driver.c main2.c pile.c
OBJ=$(SRC:.c=.o)

%.o:	%.c
	$(CC) -c $(CFLAGS) $< 

gametxt:	$(OBJ)
	$(CC) $(LINK) $(OBJ) -o $@

clean:
	rm *.o gametxt
